NANOSECONDS: int = 1
MICROSECONDS: int = 1000 * NANOSECONDS
MILISECONDS: int = 1000 * MICROSECONDS
SECONDS: int = 1000 * MILISECONDS
MIN_RATE: int = 4 * SECONDS
STARTING_BALANCE: int = 1000
MINING_REWARD: int = 50
MINING_REWARD_INPUT = { 'address': '*--official-mining-reward--*' }
